### ISSUE TITLE
Hang on Save As dialog when renaming the file

### ISSUE THREAD

**Issue by jgarciao** [xhorak/firefox-devedition-flatpak#128]
I use Firefox Nightly daily and it works very well except for this issue that annoys me a lot: when I want to save a file, if I change the filename, the _Save As_ dialog gets hung and I have to close or kill the browser and start over.

It also happens when saving a screenshot

**Steps to reproduce it:**

- Load any site
- Right click > Take a screenshot
- Save Full Page
- Download
-  _Save As_ dialog opens
-  Delete the proposed filename and try to write another
- The save as dialog gets stuck and now is not  possible to close it, not even clicking on _Cancel_ or _Save_ buttons. The parent window is clickable and you can click on the close button (top right) to close the browser

**About my setup**
- Debian 9.9
- GNOME 3.22.2 using X
- Nvidia Proprietary drivers (latest ones)
- flatpak 1.2.4-1-bpo9+1 and xdg-desktop-portal-gtk  1.2.0-1-bpo9+1 from debian-backports

**Comment by rugk** [comment]
> Save As dialog opens

It's likely your browser config, because in my case/by default the Firefox screenshots tool just automatically saves it in the Downloads dir. (no "save as" opens)

But you can obviously e.g. just right-click on an image and choose "save as" on a website.

---

I could not reproduce your issue.

In general the issue seems to be one in flatpak, respectively in [their desktop portals](https://github.com/flatpak/xdg-desktop-portal). 
But anyway, given that your flatpak and xdg-desktop-portal-gtk version are a little outdated (I have 1.4.2 here) and maybe your desktop environment too (that would be good to know), I guess it is already fixed or so.

At least it does not belong here…

**Comment by jgarciao** [comment]
You were right. The error was on my side. I fixed it running this command:
```
flatpak permission-reset org.mozilla.FirefoxNightly
```
Thanks!
