### ISSUE TITLE
Cannot build due to GPG_SETTINGS

### ISSUE THREAD

**Issue by rexcze** [xhorak/firefox-devedition-flatpak#2]
Hello I can not run build.sh script:
./build.sh
+ rm -rf app
+ APP_NAME=org.mozilla.FirefoxDevEdition
./build.sh: řádek 8: GPG_SETTINGS: unbound variable

**Comment by xhorak** [comment]
Thanks for the report, I've removed the requirement for the `GPG_SETTINGS` variable. So it don't have to be set in order to make unsigned build.

If you want to sign the build you need to have `GPG_SETTINGS` environment variable set to something like: `GPG_SETTINGS=--gpg-sign=KEYID` where `KEYID` is obtained from `gpg --list-keys`
output is something like:
`pub   2048R/KEYID 2016-12-06`
`uid                  Jan Horak (Flatpak keys) <jhorak@redhat.com>`
