### ISSUE TITLE
[FirefoxNightlyWayland] Can't copy/paste between tabs

### ISSUE THREAD

**Issue by nielsdg** [xhorak/firefox-devedition-flatpak#27]
Steps to reproduce:
* Copy some text from one tab
* Open a new tab and try to paste
* Firefox freezes, often (always?) needs to be killed forcefully

**Comment by jkonecny12** [comment]
Hello, I have the same issue. It is enough to just copy something in a system and try to paste it to the browser.

**Comment by Ramblurr** [comment]
I also can't copy paste from a firefox nightly tab into another program (e.g, terminal or gedit)

**Comment by pkgw** [comment]
I think I am seeing basically the same problem. I cannot paste text into a Firefox Nightly Wayland window anywhere; doing so causes the process to lock up. It looks like a deadlock because it is neither consuming CPU nor making syscalls. I can copy text *from* Firefox windows just fine. Running on Fedora 27.

**Comment by wvengen** [comment]
In Feb 2018, [this fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1434572) was merged, please report back if the problem still occurs for you.
