### ISSUE TITLE
Opening an URI from the command line fails to work on Wayland

### ISSUE THREAD

**Issue by linkmauve** [xhorak/firefox-devedition-flatpak#66]
It used to work in the org.mozilla.FirefoxNightlyWayland flatpak, but ever since you switched to org.mozilla.FirefoxNightly it now blocks for a few seconds, and then says that Firefox is already running.

I haven’t tested under Xwayland, as I couldn’t find the option to force it to use X11.

It could be a dbus sandbox issue, as d-feet couldn’t find any Firefox name on the session bus.

**Comment by stransky** [comment]
That's https://bugzilla.mozilla.org/show_bug.cgi?id=1434544

**Comment by stransky** [comment]
I wonder why d-feet couldn’t find any Firefox name on the session bus, that may really be a sandbox issue.
When Firefox says that Firefox is already running that means it tries to open profile which is already locked (used) by running Firefox instance.

**Comment by linkmauve** [comment]
Yes, this profile is locked by the running Firefox instance, but it should register a certain DBus name so the second instance I run would find it.

Is there a way to see if the DBus name is actually registered inside of the bubblewrap sandbox?

**Comment by Mikaela** [comment]
I have started experiencing this on X11 assuming that if I select KDE/Openbox session on Debian Testing sddm it's X11.

**Comment by wvengen** [comment]
(_disclaimer:_ I'm not a dbus expert, so I might be wrong)

I suppose there should be a flatpak dbus policy to allow Firefox expose itself. In `/var/lib/flatpak/app/org.mozilla.FirefoxNightly/current/active/metadata` I see:
```
[Session Bus Policy]
org.freedesktop.FileManager1=talk

[System Bus Policy]
org.freedesktop.NetworkManager=talk
```

So that isn't really present.
There is the `flatpak run` option `--own-name=`, might that help?

The dbus name is `org.mozilla.firefox.<profilename>`. According to the [Firefox source](https://hg.mozilla.org/mozilla-central/file/tip/widget/xremoteclient/DBusRemoteClient.cpp#l130) the last part is a slightly cleaned profile name. I'm at loss where to find that (it's not the profile directory name).

To open Firefox without a specified profile, it also needs to be able to access `org.freedesktop.DBus` to be able to figure out the profile name (but perhaps this can also be retrieved from the user config, which might be slightly safer).

**Comment by erAck** [comment]
Meanwhile works fine.
